{% set name = "monitor-server-api" %}
{% set version = "1.0.1" %}
{% set sha256 = "3a9c778a77ca1b1f87b259a14b49f74c43dc374d2243e6b839a5ead507319304" %}
{% set md5 = "246a15525193fb6b3618afc4c151335f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  md5: {{ md5 }}

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask <2.0.0
    - flask-restx
    - flask-sqlalchemy
    - sqlalchemy
    - pandas
    - requests
    - pyyaml
    - uwsgi
    - werkzeug <2.0.0

test:
  imports:
    - monitor_api
  requires:
    - pip
  commands:
    - pip check
    - type launch-monitor-server.sh  # [not win]

about:
  home: https://github.com/CFMTech/{{ name }}
  license: MIT
  license_file: LICENSE
  summary: A REST API that can be used a central point for collecting metrics from pytest-monitor.
  description: |
    For short, monitor-server-api helps you to collect, historicize and exploit the data from your tests
    written with pytest and monitored with pytest-monitor
     * Centralize your tests results
     * bring support for *pytest-xdist* and *pytest-parallel*
     * Easy data querying through specific queries
     * Integrated library for in-script queries

  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/CFMTech/{{ name }}

extra:
  recipe-maintainers:
    - js-dieu
